require("sagacity.plugins-setup")

require("sagacity.core.colorscheme")
require("sagacity.core.options")
require("sagacity.core.keymaps")

require("sagacity.plugins.comment")
require("sagacity.plugins.lualine")
require("sagacity.plugins.telescope")
require("sagacity.plugins.nvim-cmp")
require("sagacity.plugins.lsp.mason")
require("sagacity.plugins.lsp.lspsaga")
require("sagacity.plugins.lsp.lspconfig")
require("sagacity.plugins.lsp.null-ls")
require("sagacity.plugins.treesitter")
require("sagacity.plugins.autopairs")
require("sagacity.plugins.gitsigns")
require("sagacity.plugins.indentblankline")
require("sagacity.plugins.which-key")
